### ISSUE TITLE
Data Visualisation Techniques with Examples.

### ISSUE THREAD

**Issue by prasanna-muppidwar** [ML-Nagpur/Cool-Notebooks#15]
Data visualisation is a core concept as well as building block of any Data Projects. Various Data related and Techniques and Methodologies should be added with proper practical demonstration

**Comment by Sherwin-14** [comment]
Hi , I am bit confused about this issue what sort of practical demonstration you are talking about ?

**Comment by prasanna-muppidwar** [comment]
Hey , Practical Demonsatration here as in Performing Various Visualisation Techniques Charts , Graphs , Heat Maps and Corelation Charts on a Dataset with a bit of explainations in comments or text format such as when to use this why to use.

**Comment by Sherwin-14** [comment]
Ok ,can i take up this issue?

**Comment by prasanna-muppidwar** [comment]
For Sure Sherwin!

**Comment by Sherwin-14** [comment]
Should i use juypter notebook or should i create a python project with Readme for explanation

**Comment by prasanna-muppidwar** [comment]
I would suggest Using a Juypter Notebook as it would be easier to view results and graphs

**Comment by Sherwin-14** [comment]
Thanks for the help, is there a deadline for this? i am asking this since i am beginner.

**Comment by prasanna-muppidwar** [comment]
Yup one Needs to Submit in 7 days of issue Assigned as we are continiously updating the the repository.

**Comment by Sherwin-14** [comment]
Thanks.
